- name: Retrieve User Password Information
  hosts: localhost
  gather_facts: no
  vars:
    tenant_id: "your-tenant-id"
    client_id: "your-client-id"
    client_secret: "your-client-secret"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    username: "{{ user_principal_name }}"  # Pass this as extra var or through AWX payload

  tasks:
    - name: Get Azure Access Token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure Token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    - name: Reset User Password
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ username }}/authentication/passwordMethods/1/resetPassword"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body: 
          newPassword: "NewTemp@Password123!"
        body_format: json
      register: password_reset_result

    - name: Debug Password Reset
      debug:
        msg: 
          - "Password Reset Status: {{ password_reset_result.status }}"
          - "Temporary Password: NewTemp@Password123!"
